### ISSUE TITLE
Работа с разделами

### ISSUE THREAD

**Issue by niksamokhvalov** [niksamokhvalov/demo.adminhelper#2]
Добавить пример работы с зависимыми хелперами. Например, сделать категории новостей.

**Comment by unnamed777** [comment]
Имеется ли хотя бы нерабочий пример того, как правильно разделы использовать? Пытаюсь их завести, но слишком много неоднозначностей. Не нужно решения "нажал кнопку и заработало", просто классы интерфейсов и хелперов элементов и разделов, чтобы понять, как правильно использовать.

**Comment by niksamokhvalov** [comment]
Давайте я поищу в старых проектах, пришлю описание и примеры, вы попробуете сделать разделы у себя, и если получится, пришлёте ПР с доработкой демки?

**Comment by unnamed777** [comment]
Не могу гарантировать, что это случится в ближайшем будущем (думаю, глядя на дату этого тикета и ссылки-комментария к связанному посту в блоге, вы это прекрасно понимаете:-); именно с этого поста я сюда и попал, когда надоело мучать основной модуль adminhelper). Было бы достаточно просто непричёсанных примеров кода без траты времени на дополнительные описания, чтобы понять задуманную логику и в правильном направлении ли я двигаюсь.

**Comment by niksamokhvalov** [comment]
Примерно так…

1. Создаём две модели — `NewsTable` и `CategoriesTable`.
2. Создаём `NewsAdminInterface`, `NewsListHelper`, `NewsEditHelper`.
3. Создаём `CategoriesAdminInterface`, `CategoriesListHelper` (наследник `\DigitalWand\AdminHelper\Helper\AdminSectionListHelper`), `CategoriesEditHelper` (наследник `\DigitalWand\AdminHelper\Helper\AdminSectionEditHelper`).
4. В `NewsAdminInterface` прописываем зависимость:
```php
public function dependencies()
{
	return [CategoriesAdminInterface::class];
}
```
5. В `CategoriesAdminInterface` прописываем зависимость:
```php
public function dependencies()
{
	return [NewsAdminInterface::class];
}
```

**Comment by unnamed777** [comment]
Спасибо, уже сам разобрался. По ошибке указывал в helpers у элементов хелперы от раздела. Плюс кое-какие проблемы с колонками были, по ним PR сделал.

**Comment by nook-ru** [comment]
@niksamokhvalov,
> Давайте я поищу в старых проектах, пришлю описание и примеры, вы попробуете сделать разделы у себя, и если получится, пришлёте ПР с доработкой демки?

Я готов сделать PR с примером для разделов. Весьма не очевидна работа с ними, как ни крути, получаются независимые модели. Как организовать навигацию решительно непонятно)

**Comment by unnamed777** [comment]
@nook-ru модели и должны быть разные - модель для сущности и модель для разделов. Вот мой [пример](https://gist.github.com/unnamed777/cf6e7619e72bda1d4fc75cc1235a72ed) из рабочего проекта (модели для админки, хелперы для обоих сущностей, модели сущностей (*Table)). Но чтобы это всё завести, пришлось внести исправления в модуль, они отлёживаются в [PR](https://github.com/DigitalWand/digitalwand.admin_helper/pull/67) сейчас.

ЗЫ: названия хелперов у меня отличаются от модуля, потому как использую свои классы-наследники, позволяющие не делать модуль на каждую сущность в админке, но в целом, надеюсь, это поможет понять логику.

**Comment by nook-ru** [comment]
@unnamed777, спасибо за пример, очень помог. Чтобы пазл сошёлся, не хватало [`SECTION_LINK`](https://gist.github.com/unnamed777/cf6e7619e72bda1d4fc75cc1235a72ed#file-section-php-L34), в `phpDoc` нигде не упоминающегося.

А вот статические [`$useSections` и `$sectionSuffix`](https://github.com/DigitalWand/digitalwand.admin_helper/blob/2.x/lib/helper/AdminBaseHelper.php#L260) из хелперов, несмотря на комментарии, по факту никак не используются.

> модели и должны быть разные - модель для сущности и модель для разделов

Частенько бывают кейсы с одной сущностью, которой просто нужно добавить иерархию. Тогда и «разделы» и «элементы» будут в одной модели.
