### ISSUE TITLE
Добавление ссылок "Редактировать/удалить" элемент

### ISSUE THREAD

**Issue by Agronya** [niksamokhvalov/demo.adminhelper#3]
Добрый день, спасибо за проделанную работу, очень нужный в работе инструмент. Не могу понять, как в списке элементов сделать контекстное меню с ссылками "редактировать", "удалить"?. Вроде всё сделал как в демо примере, а кнопок нет.

**Comment by niksamokhvalov** [comment]
Привет! Контекстное меню с кнопками «Редактировать» и «Удалить» появляются по-умолчанию, их не надо кодить.

Добавить дополнительные кнопки или изменить значения по-умолчанию можно в методе [`getRowActions`](https://github.com/DigitalWand/digitalwand.admin_helper/blob/0471a05303073be89fe290253903b49a07e896eb/lib/helper/AdminListHelper.php#L1301-L1358) лист-хелпера, например:

```
<?php

class SomeListHelper extends \DigitalWand\AdminHelper\Helper\AdminListHelper
{
    protected function getRowActions($data)
    {
        $actions = parent::getRowActions($data);

        // Для красоты вставляем разделительную линию.
        $actions[] = ['SEPARATOR' => true];

        $actions['some_button'] = [
            'ICON' => false,
            'TEXT' => 'Заголовок',
            'ACTION' => /*Действие, которое необходимо выполнить*/,
        ];

        return $actions;
    }
}
```
